/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n8.0.1-48-g0592be14ff-20260116"
#endif /* AVUTIL_FFVERSION_H */
